### PR TITLE
Added a Dictionary widget

### PR DESCRIPTION
**Pull request by AMKohn**
Screenshots:

Default state Expanded

### CODE REVIEW

**Comment by thinkingmedia** [comment]
:+1: great widget! Just noticed this now. Going to add this to my tab.

**Comment by AMKohn** [comment]
@thinkingmedia Thanks. Only problem is it'll only work with a key....

**Comment by thinkingmedia** [comment]
That sucks. You could make the key part of the configuration but that adds a complex step most users wouldn't understand.

I found this dictionary API. Looks like it doesn't require a key.

http://services.aonaware.com/DictService/DictService.asmx

**Comment by AMKohn** [comment]
I'm actually moving the API to the server right now. I decided that the request shouldn't be made client side due to the nature of that API (unofficial).

I'm 10 minutes from committing.

**Comment by thinkingmedia** [comment]
Server would be better. You might want to reformat the response. That way in the future if you change API providers you don't have to update the client.

**Comment by AMKohn** [comment]
That's the idea behind the server itself. Reformatting already done, just cleaning up.

**Comment by AMKohn** [comment]
OK. Committed and rolled the API update out to the servers.

**Comment by thinkingmedia** [comment]
:+1: great job man.

**Pull request merged**
