### PR TITLE
Tab nav "fixed" position

### PR DESCRIPTION
**Pull request by BenDz**

### CODE REVIEW

**Comment by AMKohn** [comment]
Thank you for the pull, but this change places the tab-nav element over the toolbar making it unusable. Plus, the nav buttons are already nearly centered. Why is it necessary?

**Comment by BenDz** [comment]
Hi, you're right, I didn't see that. It works better when putting ".tab-nav nav" to position fixed - I can create a new pull request for it if needed.
In my case, my tab is 2 scroll long, then when I'm at the bottom of the tab, I have to scroll up to change tab.
Thanks, Ben

**Comment by AMKohn** [comment]
No need, but the change removes the need for any sort of styling on the parent element.

I figured at that point I might as well update the nav buttons entirely so they're actual buttons (nav elements shouldn't be used like that) and are centered properly. I just did that (770e18dd5439d1ca79c7411de37f5d94a0efddbe), but I don't want to take credit from you by taking your name off it.

Do you want to maybe fork the branch and pull again or something? Or maybe I can merge your pull and then merge the feature branch?

**Comment by BenDz** [comment]
You can take my name off of it, no problem :)
Thanks!

**Comment by AMKohn** [comment]
OK. Thank you for the pull and suggestion!

**Pull request closed without merging**
